
$ROOT_PATH="$PSScriptRoot" + "\.."
$SUNDIALS_BUILD_PATH="$ROOT_PATH" + "\thirdparty\sundials\build"
$SUNDIALS_INSTALL_PATH="$ROOT_PATH" + "\thirdparty\sundials\install"

$BUILD_TYPE="Release"

ni $SUNDIALS_BUILD_PATH
ni $SUNDIALS_INSTALL_PATH

cd $SUNDIALS_BUILD_PATH

cmake -DCMAKE_INSTALL_PREFIX="$SUNDIALS_INSTALL_PATH" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DEXAMPLES_ENABLE_C=OFF ..
