name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test-macos-windows:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - macos-clang
          - windows-msvc

        configuration:
          - Debug

        include:
          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure (${{ matrix.configuration }})
        run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build

      - name: Test
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}

  build-and-memtest-linux:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - macos-clang

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y valgrind
          valgrind --version

      - name: Configure (${{ matrix.configuration }})
        run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build

      - name: Test
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}

      - name: Memory check on linux
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }} -T memcheck 2>&1 | tee memcheck.log

      - name: Check memcheck for leaks
        if: ${{ matrix.toolchain == 'linux-gcc'}}
        working-directory: build
        run: |
          if grep -q "Defects:" "memcheck.log"; then
            echo "Defeacts are found by memcheck:"
            ls -la Testing/Temporary/MemoryChecker.*.log
            cat Testing/Temporary/MemoryChecker.*.log
            exit 1
          fi
