name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - linux-gcc

        configuration:
          - Debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build Sundials
        run: |
          scripts/buildSundials.sh

      - name: Install dependencies
        run: |
          sudo apt-get install -y valgrind
          valgrind --version

      - name: Configure (${{ matrix.configuration }})
        run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build

      - name: Test
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}

      - name: Memory check on linux
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }} -T memcheck 2>&1 | tee memcheck.log

      - name: Check memcheck for leaks
        if: ${{ matrix.toolchain == 'linux-gcc'}}
        working-directory: build
        run: |
          if grep -q "Defects:" "memcheck.log"; then
            echo "Defeacts are found by memcheck:"
            ls -la Testing/Temporary/MemoryChecker.*.log
            cat Testing/Temporary/MemoryChecker.*.log
            exit 1
          fi
