name: CI windows

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        toolchain:
          - windows-msvc

        configuration:
          - Debug

        include:
          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ''
      - name: Conda Environment
        shell: powershell
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv

      - name: Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: $HOME\clcache
          key: ${{ runner.os }}-clcache

      - name: Build SUNDIALS
        shell: powershell
        run: |
          scripts\buildSundials.ps1
